### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by mavilein** [Roconda/docker-postgres-logging#3]
Hey,

i could not find you on Twitter so i just wanted to quickly thank you for maintaining this image! This will increase my daily life quite a bit :)

**Comment by Roconda** [comment]
Hi mavilein!

Thanks a lot for these kind words, it means a lot to me!

Ironically I don't use this docker image a lot. So if I'm lacking behind, don't hesitate to make a pull request. It will also automatically appear on [docker hub](https://hub.docker.com/r/timms/postgres-logging) :-)
